# Generated by Django 4.1.1 on 2022-10-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(related_name='blog_posts', to='blog.topic'),
        ),
    ]
